### ISSUE TITLE
NullPointerException at: ZUGFeRDExporter.PDFattachZugferdFile(this)

### ISSUE THREAD

**Issue by 321drago** [ZUGFeRD/mustangproject#145]
Hello everybody,
i have a java project (Netbeans) and try to create a zugferd pdf invoice. I added the mustang-1.7.5.jar (within pdfbox) and copied the example: MustangWriter from [the project](https://github.com/ZUGFeRD/mustangproject/blob/master/doc/MustangWriter.java).
When i try to export a pdf with custom xml (.setZUGFeRDXMLData) it works, but when i try the .PDFattachZugferdFile(this) i get a exception. Maybe i use the wrong syntax to create the pdf? From the example MustangWriter.java i just changed the input und output pdfpath+name and put it completely at projectmain. I have also 4 warnings "method does not override or implement a method from a supertype" for: getOwnBIC(), getOwnBankName(), getOwnIBAN(), getOwnPaymentInfoText().

This is the exception:
`Exception in thread "main" java.lang.NullPointerException
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.getPaymentData(ZUGFeRDTransactionModelConverter.java:452)
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.getTradeSettlement(ZUGFeRDTransactionModelConverter.java:427)
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.getTradeTransaction(ZUGFeRDTransactionModelConverter.java:185)
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.convertToModel(ZUGFeRDTransactionModelConverter.java:101)
	at org.mustangproject.ZUGFeRD.ZUGFeRD1PullProvider.createZugferdXMLForTransaction(ZUGFeRD1PullProvider.java:77)
	at org.mustangproject.ZUGFeRD.ZUGFeRD1PullProvider.generateXML(ZUGFeRD1PullProvider.java:104)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporter.PDFattachZugferdFile(ZUGFeRDExporter.java:393)`

Thank you very much and best regards, I hope someone can help.

**Comment by jstaerk** [comment]
apologies I corrected the sample
