### ISSUE TITLE
problem error checking file as pdf/a

### ISSUE THREAD

**Issue by dashandwerk** [ZUGFeRD/mustangproject#164]
I have tested this project to combine pdf/a document with xml meta data.
But my pdf/a file is ignorred and an error is generated.
[Standard_pdfa.pdf](https://github.com/ZUGFeRD/mustangproject/files/4739813/Standard_pdfa.pdf)

**Comment by jstaerk** [comment]
which error and how do you invoke it?

if you use the library there is a option to ignore errors, e.g. verapdf seems to validate the file but at the same time a 
SCHWERWIEGEND: Font object is not a dictionary
is logged

**Comment by dashandwerk** [comment]
Hi Jochen,

 

i am using java -jar mustang-1.7.7.jar -c

 

Then following the steps.

Input pdf file is attached 

Input xml file is attached

 

And then this error occurs:

 

Jun 06, 2020 12:16:09 PM org.mustangproject.toecount.Toecount performCombine

SCHWERWIEGEND: null

java.io.IOException: File is not a valid PDF/A input file

        at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.ensurePDFIsValidPDFA(ZUGFeRDExporterFromA3Factory.java:106)

        at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.load(ZUGFeRDExporterFromA3Factory.java:65)

        at org.mustangproject.toecount.Toecount.performCombine(Toecount.java:546)

        at org.mustangproject.toecount.Toecount.main(Toecount.java:327)

 

Mit freundlichem Gruß

Frank Lehmann
Geschäftsführer


dashandwerk.net
Frank Lehmann
Lindenstrasse 10a
28755 Bremen

Tel: +49 (0) 421 56507289
Mail: info@dashandwerk.net <mailto:info@dashandwerk.net> 
Web: www.dashandwerk.net <http://www.dashandwerk.net/> 
Datenschutz: https://handwerkersoftware-mieten.de/datenschutz/


Wir verstehen ihr Handwerk 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. 
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte 
sofort den Absender und vernichten Sie diese E-Mail. 
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sowie von Teilen dieser E-Mail ist nicht 
gestattet.

P Nicht vergessen: auch an die Umwelt denken! Ein Ausdruck ist nicht immer nötig.

 

Von: Jochen Staerk <notifications@github.com> 
Gesendet: Samstag, 6. Juni 2020 13:12
An: ZUGFeRD/mustangproject <mustangproject@noreply.github.com>
Cc: dashandwerk <info@dashandwerk.net>; Author <author@noreply.github.com>
Betreff: Re: [ZUGFeRD/mustangproject] problem error checking file as pdf/a (#164)

 

which error and how do you invoke it?

if you use the library there is a option to ignore errors, e.g. verapdf seems to validate the file but at the same time a
SCHWERWIEGEND: Font object is not a dictionary
is logged

**Comment by dashandwerk** [comment]
Hi Jochen,

 

there is no parameter to ignore errors.

 

Usage: [-d,--directory] [-l,--listfromstdin] [-i,--ignorefileextension] | [-c,--combine] | [-e,--extract] | [-u,--upgrade] | [-a,--a3only] | [-h,--help]

 

Mit freundlichem Gruß

Frank Lehmann
Geschäftsführer


dashandwerk.net
Frank Lehmann
Lindenstrasse 10a
28755 Bremen

Tel: +49 (0) 421 56507289
Mail: info@dashandwerk.net <mailto:info@dashandwerk.net> 
Web: www.dashandwerk.net <http://www.dashandwerk.net/> 
Datenschutz: https://handwerkersoftware-mieten.de/datenschutz/


Wir verstehen ihr Handwerk 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. 
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte 
sofort den Absender und vernichten Sie diese E-Mail. 
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sowie von Teilen dieser E-Mail ist nicht 
gestattet.

P Nicht vergessen: auch an die Umwelt denken! Ein Ausdruck ist nicht immer nötig.

 

Von: Jochen Staerk <notifications@github.com> 
Gesendet: Samstag, 6. Juni 2020 13:12
An: ZUGFeRD/mustangproject <mustangproject@noreply.github.com>
Cc: dashandwerk <info@dashandwerk.net>; Author <author@noreply.github.com>
Betreff: Re: [ZUGFeRD/mustangproject] problem error checking file as pdf/a (#164)

 

which error and how do you invoke it?

if you use the library there is a option to ignore errors, e.g. verapdf seems to validate the file but at the same time a
SCHWERWIEGEND: Font object is not a dictionary
is logged

**Comment by dashandwerk** [comment]
Hi Jochen,




it is possible, to convert normal pdf to pdf/a and then combine with xml ?




Mit freundlichem Gruß






dashandwerk.net


Lindenstrasse 10a


28755 Bremen






Tel: 0421 - 56507289


Mail: info@dashandwerk.net


Web: https://www.dashandwerk.net







On Sat, Jun 6, 2020 at 1:12 PM +0200, "Jochen Staerk" <notifications@github.com> wrote:















which error and how do you invoke it?


if you use the library there is a option to ignore errors, e.g. verapdf seems to validate the file but at the same time a

SCHWERWIEGEND: Font object is not a dictionary

is logged

**Comment by jstaerk** [comment]
Hi,I've talked with some PDF guys and we (except V. whose sample file was invalid) consider it impossible to filter PDF to become PDF/A so the only viable solution seems to render the PDF and import it into PDF/A, like as if you virtually printed it but retaining vector data.

-> converting PDF to PDF/A is unfortunately a monumental task and I recommend ghostscript for it. That would be something like  downloading Adobe ICC profiles from https://www.adobe.com/support/downloads/iccprofiles/icc_eula_win_end.html,

adjust your ghostscripts /usr/local/share/ghostscript/9.18/lib/PDFA_def.ps to use the downloaded ICC file, e.g. with the line /ICCProfile (/Users/jstaerk/AdobeRGB1998.icc) 
and then something like 
```
gs -dPDFA=1 -dNOOUTERSAVE -sProcessColorModel=DeviceRGB -sDEVICE=pdfwrite -o factur-x-pdfa.pdf -dPDFACompatibilityPolicy=1 /usr/local/share/ghostscript/9.18/lib/PDFA_def.ps factur-x.pdf
```
Please note that it's also possible to create zugferd pdf/a-3 with ghostscript https://bugs.ghostscript.com/show_bug.cgi?id=696472

Anyway the ingres validation is based on PDFbox, which, in general, validates much less than VeraPDF but at the same time so far never had had any false postives. So I do recommend to follow up on that error. Anyway, to get you going, I abused the -i parameter to ignore input PDF/A errors (the output will most likely not be any more valid than the input, probably drastically less), 
try 
http://mustangproject.org/files/Mustang-CLI-2.0.0-SNAPSHOT.jar
it *could* be something like
`java -jar Mustang-CLI-2.0.0-SNAPSHOT.jar -i --action combine`
actually I never tested it.

**Comment by dashandwerk** [comment]
Hi Jochen,

 

validation of attached file is correct.

See screenshot



 

Mit freundlichem Gruß

Frank Lehmann
Geschäftsführer


dashandwerk.net
Frank Lehmann
Lindenstrasse 10a
28755 Bremen

Tel: +49 (0) 421 56507289
Mail: info@dashandwerk.net <mailto:info@dashandwerk.net> 
Web: www.dashandwerk.net <http://www.dashandwerk.net/> 
Datenschutz: https://handwerkersoftware-mieten.de/datenschutz/


Wir verstehen ihr Handwerk 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. 
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte 
sofort den Absender und vernichten Sie diese E-Mail. 
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sowie von Teilen dieser E-Mail ist nicht 
gestattet.

P Nicht vergessen: auch an die Umwelt denken! Ein Ausdruck ist nicht immer nötig.

 

Von: Jochen Staerk <notifications@github.com> 
Gesendet: Samstag, 6. Juni 2020 13:49
An: ZUGFeRD/mustangproject <mustangproject@noreply.github.com>
Cc: dashandwerk <info@dashandwerk.net>; Author <author@noreply.github.com>
Betreff: Re: [ZUGFeRD/mustangproject] problem error checking file as pdf/a (#164)

 

Hi,I've talked with some PDF guys and we (except V. whose sample file was invalid) consider it impossible to filter PDF to become PDF/A so the only viable solution seems to render the PDF and import it into PDF/A, like as if you virtually printed it but retaining vector data.

-> converting PDF to PDF/A is unfortunately a monumental task and I recommend ghostscript for it. That would be something like downloading Adobe ICC profiles from https://www.adobe.com/support/downloads/iccprofiles/icc_eula_win_end.html,

adjust your ghostscripts /usr/local/share/ghostscript/9.18/lib/PDFA_def.ps to use the downloaded ICC file, e.g. with the line /ICCProfile (/Users/jstaerk/AdobeRGB1998.icc)
and then something like

gs -dPDFA=1 -dNOOUTERSAVE -sProcessColorModel=DeviceRGB -sDEVICE=pdfwrite -o factur-x-pdfa.pdf -dPDFACompatibilityPolicy=1 /usr/local/share/ghostscript/9.18/lib/PDFA_def.ps factur-x.pdf

Please note that it's also possible to create zugferd pdf/a-3 with ghostscript https://bugs.ghostscript.com/show_bug.cgi?id=696472

Anyway the ingres validation is based on PDFbox, which, in general, validates much less than VeraPDF but at the same time so far never had had any false postives. So I do recommend to follow up on that error. Anyway, to get you going, I abused the -i parameter to ignore input PDF/A errors (the output will most likely not be any more valid than the input, probably drastically less),
try
http://mustangproject.org/files/Mustang-CLI-2.0.0-SNAPSHOT.jar
it could be something like
java -jar Mustang-CLI-2.0.0-SNAPSHOT.jar -i --action combine
actually I never tested it.

**Comment by jstaerk** [comment]
see also #139
