### ISSUE TITLE
Getting error java.io.IOException: File is not a valid PDF/A input file for PDF/A-1b 

### ISSUE THREAD

**Issue by DivyaAppidi** [ZUGFeRD/mustangproject#167]
Hi Team
We generate the PDF using a print manager and it supports only PDF/A-1b documents. However when I run the mustang.jar command to generate a ZUGfERD PDF, I get an error that it is not a valid PDF/A input file.
Does mustang.jar not support PDF/A-1b input files? If not, any parameter that we can use to ignore this validation?
I am using "java -jar mustang-1.7.8.jar -c" command line for generating the output PDF

**Comment by jstaerk** [comment]
Hi,
yes,PDF/A-1b input is supported, unfortunately the PDFBox validation can be very strict, in some cases stricter than e.g. verapdf. Since 2.0alpha you can use the -i parameter to ignore this kind of errors, try mustangproject.org/files/Mustang-CLI-2.0.0-SNAPSHOT.jar
kind regards
Jochen

**Comment by DivyaAppidi** [comment]
Hi,
I have tried the below, but I still get the validation error. Can you please help me ignore the validation?

java -jar Mustang-CLI-2.0.0-SNAPSHOT.jar  --action combine -i --source OInvoice.pdf --source-xml ZUGFeRD-invoice.xml --out zugferd-invoice.pdf  --format zf --version 1 --profile E

Source PDF set to OInvoice.pdf
ZUGFeRD XML set to ZUGFeRD-invoice.xml
Ouput PDF set to zugferd-invoice.pdf
Format set to zf
Version set to 1
Profile set to E
Jun 23, 2020 5:25:47 PM org.mustangproject.commandline.Main performCombine
SEVERE: null
java.io.IOException: File is not a valid PDF/A input file
        at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.ensurePDFIsValidPDFA(ZUGFeRDExporterFromA3Factory.java:106)
        at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.load(ZUGFeRDExporterFromA3Factory.java:65)
        at org.mustangproject.commandline.Main.performCombine(Main.java:584)
        at org.mustangproject.commandline.Main.main(Main.java:312)

**Comment by DivyaAppidi** [comment]
Hi Team
Yes, we have tried using the ignore option, but we still get the error.

Test1:
java -jar Mustang-CLI-2.0.0-SNAPSHOT.jar --action combine -i --source OInvoice.pdf --source-xml ZUGFeRD-invoice.xml --out zugferd-invoice.pdf --format zf --version 1 --profile E
Source PDF set to OInvoice.pdf
ZUGFeRD XML set to ZUGFeRD-invoice.xml
Ouput PDF set to zugferd-invoice.pdf
Format set to zf
Version set to 1
Profile set to E
Jun 23, 2020 5:25:47 PM org.mustangproject.commandline.Main performCombine
SEVERE: null
java.io.IOException: File is not a valid PDF/A input file
at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.ensurePDFIsValidPDFA(ZUGFeRDExporterFromA3Factory.java:106)
at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.load(ZUGFeRDExporterFromA3Factory.java:65)
at org.mustangproject.commandline.Main.performCombine(Main.java:584)
at org.mustangproject.commandline.Main.main(Main.java:312)
Test2:
java -jar Mustang-CLI-2.0.0-SNAPSHOT.jar  --action combine -i --source InvoiceTest.pdf  --source-xml ZUGFeRD-invoice.xml --out zugferd-invoice.pdf  --format zf --version 1 --profile E

Source PDF set to InvoiceTest.pdf
ZUGFeRD XML set to ZUGFeRD-invoice.xml
Ouput PDF set to zugferd-invoice.pdf
Format set to zf
Version set to 1
Profile set to E
Jun 25, 2020 2:21:35 PM org.mustangproject.commandline.Main performCombine
SEVERE: null
org.apache.pdfbox.preflight.exception.SyntaxValidationException
                at org.apache.pdfbox.preflight.parser.PreflightParser.parse(PreflightParser.java:257)
                at org.apache.pdfbox.preflight.parser.PreflightParser.parse(PreflightParser.java:234)
                at org.apache.pdfbox.preflight.parser.PreflightParser.parse(PreflightParser.java:222)
                at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.getPDFAParserValidationResult(ZUGFeRDExporterFromA3Factory.java:136)
                at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.isValidA1(ZUGFeRDExporterFromA3Factory.java:117)
                at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.ensurePDFIsValidPDFA(ZUGFeRDExporterFromA3Factory.java:105)
                at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.load(ZUGFeRDExporterFromA3Factory.java:65)
                at org.mustangproject.commandline.Main.performCombine(Main.java:584)
                at org.mustangproject.commandline.Main.main(Main.java:312)

Can you please help us with this, to ignore the validation errors?

Thanks and Regards,
Divya

**Comment by KevinvanderHoeven83** [comment]
Hi Team,

Would it be possible to have a look at the question that is raised by @DivyaAppidi  ? 
As we need this really urgently. 

Your help is much appreciated.

Kind regards
Kevin

**Comment by DivyaAppidi** [comment]
Attaching one of the sample PDFs if it helps
[InvoiceTest.pdf](https://github.com/ZUGFeRD/mustangproject/files/4835941/InvoiceTest.pdf)

**Comment by jstaerk** [comment]
as mentioned in https://github.com/ZUGFeRD/mustangproject/issues/164#issuecomment-640046774 I recommend Ghostscript for that, I installed 9.52 in c:\gs, copied it's lib\PDFA_def.ps to my download folder, downloaded and extracted the adobe ICC color profiles (https://www.adobe.com/support/downloads/iccprofiles/iccprofiles_win.html) there, adjusted srgb.icc in  PDFA_def.ps and ran 
`\gs\bin\gswin64.exe -P -dPDFA=1 -sColorConversionStrategy=RGB -sDEVICE=pdfwrite -oOut.pdf -dPDFACompatibilityPolicy=1 -dRenderIntent=3  PDFA_def.ps InvoiceTest.pdf` (in my download folder) which produced 
[Out.pdf](https://github.com/ZUGFeRD/mustangproject/files/5169193/Out.pdf) which should be your file converted to proper pdf/a (I checked with verapdf), I hope that helps
