### ISSUE TITLE
Wildfly jaxb problem

### ISSUE THREAD

**Issue by andrm** [ZUGFeRD/mustangproject#174]
I can't get 1.7.8 running in wildfly 19 or 20 and java 11. 
Error:  Unhandled exception: org.mustangproject.ZUGFeRD.ZUGFeRDExportException: Could not initialize JAXB
Caused by: javax.xml.bind.PropertyException: Eigenschaft "com.sun.xml.bind.namespacePrefixMapper" muss eine Instanz vom Typ com.sun.xml.bind.marshaller.NamespacePrefixMapper sein, und nicht org.mustangproject.ZUGFeRD.model.ZFNamespacePrefixMapper
	at com.sun.xml.bind@2.3.3-b02//com.sun.xml.bind.v2.runtime.MarshallerImpl.setProperty(MarshallerImpl.java:499)
	at deployment.XXXX-1.5-SNAPSHOT.war//org.mustangproject.ZUGFeRD.ZUGFeRD1PullProvider.<init>(ZUGFeRD1PullProvider.java:67)

If I run the code as a standalone application, it works. Seems to me a classloader/classpath problem.

**Comment by jstaerk** [comment]
Jaxb has been removed from Mustang 2, can you try the alpha?

**Comment by andrm** [comment]
Yes, but tests fail. Is the "library-2.0.0-SNAPSHOT.jar" the correct jar to use?

**Comment by andrm** [comment]
Ok, built it myself and deployed it locally. ZfExporter is gone, so I tried with XRExporter, Result:
Caused by: java.lang.NullPointerException
	at deployment.XXX-1.5-SNAPSHOT.war//org.mustangproject.ZUGFeRD.XRExporter.export(XRExporter.java:71)

which is this: xmlProvider.generateXML(trans);
I don't see where xmlProvider is initialized....

**Comment by jstaerk** [comment]
it's not, fixed in the master head but so far pls use setZUGFeRDVersion like described in  https://github.com/ZUGFeRD/mustangproject/blob/master/Release_Notes.md#embedding-the-validator

**Comment by jstaerk** [comment]
jaxb has been removed in v2 altogether
