### ISSUE TITLE
Problem getting started with MustangWriter

### ISSUE THREAD

**Issue by dularion** [ZUGFeRD/mustangproject#177]
So we have a JAVA / Groovy project and we wanna use Mustang to generate XRechnung for a german client - we are german ourselves, so if you prefer german communication, thats cool too. Now we tried to simply use our existing invoicing PDFs and injecting the XRechnung XML into it using "PDFattachZugpferdFile" but when we try this, we get this error: 

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.graphics.color.PDICCBased.create(Lorg/apache/pdfbox/cos/COSArray;Lorg/apache/pdfbox/pdmodel/PDResources;)Lorg/apache/pdfbox/pdmodel/graphics/color/PDICCBased;
	at org.apache.pdfbox.preflight.process.CatalogValidationProcess.validateICCProfile(CatalogValidationProcess.java:366)
	at org.apache.pdfbox.preflight.process.CatalogValidationProcess.validateOutputIntent(CatalogValidationProcess.java:288)
	at org.apache.pdfbox.preflight.process.CatalogValidationProcess.validate(CatalogValidationProcess.java:151)
	at org.apache.pdfbox.preflight.utils.ContextHelper.callValidation(ContextHelper.java:102)
	at org.apache.pdfbox.preflight.utils.ContextHelper.validateElement(ContextHelper.java:141)
	at org.apache.pdfbox.preflight.PreflightDocument.validate(PreflightDocument.java:166)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.getPDFAParserValidationResult(ZUGFeRDExporterFromA3Factory.java:145)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.isValidA1(ZUGFeRDExporterFromA3Factory.java:117)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.ensurePDFIsValidPDFA(ZUGFeRDExporterFromA3Factory.java:105)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3Factory.load(ZUGFeRDExporterFromA3Factory.java:65)
	at mustangtest.MustangWriter.apply(MustangWriter.java:142)
	at mustangtest.MustangWriter.main(MustangWriter.java:156)
```

This is the code we try to use, as a very simple example: 

```
private void apply() {
		try {
			System.out.println("Reading Blanko-PDF");
			ZUGFeRDExporter ze = new ZUGFeRDExporterFromA1Factory().setProducer("My Application")
					.setCreator(System.getProperty("user.name"))
					.load("/dev/projects/kcenter/src/main/java/MustangGnuaccountingBeispielRE-20170509_505.pdf");
			System.out.println("Generating and attaching ZUGFeRD-Data");
			ze.PDFattachZugferdFile(this);
			System.out.println("Writing ZUGFeRD-PDF");
			ze.export("./MustangGnuaccountingBeispielRE-20170509_505new.pdf");
			System.out.println("Done.");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
```

The whole file is here, its pretty much a copy-paste from your file within the /doc folder: https://gist.github.com/dularion/16de7de1efc332fd3aeebc03210fb1ae

Any idea how we could get this running? we tried looking in your PDF docs but the steps seem to be identical to your MustangWriter file and you dont mention the exception above. 

Hope that you can help us!

**Comment by jstaerk** [comment]
Hi,
there was a request for groovy but I never had the time or know how how to do it.
I see I linked https://www.mustangproject.org/deploy/original-mustang-1.7.5.jar in /use/ which is probably one of the stupider things I did, please try the most recent version *with dependencies*, i.e. https://www.mustangproject.org/deploy/mustang-1.7.8.jar and let me know if that works better.

kind regards
Jochen

**Comment by dularion** [comment]
will try, thanks for the quick response!

**Comment by dularion** [comment]
seems like we were already using 1.7.8, but we found another thing: we had included the librarby Apache Tika, which caused a conflict with PDFBox. So now that that is solved, we have another issue: https://github.com/ZUGFeRD/mustangproject/issues/139
