### ISSUE TITLE
NullPointerException at: ZUGFeRDExporter.PDFattachZugferdFile(this)

### ISSUE THREAD

**Issue by mitchneu** [ZUGFeRD/mustangproject#188]
Hello,
I copied the MustangWriter example form the project. I just changed the input and the output filename and the path to the files. When the program tries to attach the Zugferd file by calling .PDFattachZugferdFile(this), I get the following NullPointerException:

```
Exception in thread "main" java.lang.NullPointerException
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.getPaymentData(ZUGFeRDTransactionModelConverter.java:454)
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.getTradeSettlement(ZUGFeRDTransactionModelConverter.java:429)
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.getTradeTransaction(ZUGFeRDTransactionModelConverter.java:187)
	at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.convertToModel(ZUGFeRDTransactionModelConverter.java:103)
	at org.mustangproject.ZUGFeRD.ZUGFeRD1PullProvider.createZugferdXMLForTransaction(ZUGFeRD1PullProvider.java:77)
	at org.mustangproject.ZUGFeRD.ZUGFeRD1PullProvider.generateXML(ZUGFeRD1PullProvider.java:104)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporter.PDFattachZugferdFile(ZUGFeRDExporter.java:393)
	at MustangWriter.apply(MustangWriter.java:270)
	at MustangWriter.main(MustangWriter.java:283)
```

A similar error occurred in [january](https://github.com/ZUGFeRD/mustangproject/issues/145).
I also tried to attach custom XML which works just fine.

**Comment by jstaerk** [comment]
did you try the corrected sample I had mentioned on 14 jan?

**Comment by mitchneu** [comment]
Yes, I tried the newest sample. also using mustang-1.7.8.jar

**Comment by jstaerk** [comment]
hi, tweimer just submitted a patch for mustang 2 on https://github.com/ZUGFeRD/mustangproject/pull/204 does that help?

**Comment by tweimer** [comment]
Seems to be the same NullPointerException as in #165
