### ISSUE TITLE
Nullpointer Exception import zugferd

### ISSUE THREAD

**Issue by StefanSchmaltz** [ZUGFeRD/mustangproject#283]
java.lang.NullPointerException
	at org.mustangproject.ZUGFeRD.TransactionCalculator.getVATPercentAmountMap(TransactionCalculator.java:187)
	at org.mustangproject.ZUGFeRD.TransactionCalculator.getGrandTotal(TransactionCalculator.java:44)
	at org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter.extractInvoice(ZUGFeRDInvoiceImporter.java:349)

Mustang-CLI-2.5.3.jar

**Comment by jstaerk** [comment]
Hi,
Steps to reproduce? E.g. the invoice?
Thanks and kind regards
Jochen

**Comment by StefanSchmaltz** [comment]
Hi, invoice is not public.
currentAllowance.getTaxPercent() is null -->NPE
solution:
old code:
`ATAmount theAmount = hm.get(currentAllowance.getTaxPercent().stripTrailingZeros());`
new code:
`ATAmount theAmount = currentAllowance.getTaxPercent()==null?null:hm.get(currentAllowance.getTaxPercent().stripTrailingZeros());`

**Comment by jstaerk** [comment]
Does the invoice validate?

**Comment by opensprinklershop** [comment]
Yes, invoice validates
