### ISSUE TITLE
Versionen 2.5.5 und 2.5.6 laufen nicht mehr unter JAVA 8 (java version "1.8.0_341")

### ISSUE THREAD

**Issue by msccip** [ZUGFeRD/mustangproject#286]
Hallo,

Ist das bekannt ? Falls ja, sollte zumindest ein entspr. Hinweis erfolgen.

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mustangproject/validator/Validator has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.mustangproject.commandline.Main.<clinit>(Main.java:46)

**Comment by jstaerk** [comment]
Läuft die 2.5.4 noch unter Java 8? Tatsächlich steht maven.compiler.target vom Hauptprojekt weiter auf 1.8 mir wäre neu dass ich das in den Unterprojekten wiederholen muss.

**Comment by msccip** [comment]
2.5.4 läuft noch ohne Probleme

**Comment by jstaerk** [comment]
ich prüfe das nächste woche mal.
