### ISSUE TITLE
java.lang.NoSuchMethodError bei ZUGFeRDValidator seit 2.5.5

### ISSUE THREAD

**Issue by smejkal** [ZUGFeRD/mustangproject#287]
Seit der Version 2.5.5 funktioniert der Validator nicht mehr
```

final File file = new File("invoice2674401409482819052.pdf");
		
if (file != null && file.exists() && file.canRead()) {
	final ZUGFeRDValidator zfv = new ZUGFeRDValidator();
	System.out.println(zfv.validate(file.getAbsolutePath()));
}
```

Fehlermeldung:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.helger.jaxb.GenericJAXBMarshaller.<init>(java.lang.Class, java.util.List, java.util.function.Function)'
	at com.helger.schematron.svrl.SVRLMarshaller.<init>(SVRLMarshaller.java:43)
	at com.helger.schematron.api.xslt.AbstractSchematronXSLTBasedResource.applySchematronValidationToSVRL(AbstractSchematronXSLTBasedResource.java:287)
	at com.helger.schematron.AbstractSchematronResource.applySchematronValidationToSVRL(AbstractSchematronResource.java:287)
	at org.mustangproject.validator.XMLValidator.validateSchematron(XMLValidator.java:406)
	at org.mustangproject.validator.XMLValidator.validate(XMLValidator.java:331)
	at org.mustangproject.validator.ZUGFeRDValidator.validate(ZUGFeRDValidator.java:206)
```

Mit 2.5.4 und zuvor gab keine Probleme.

Vielen Dank!

--------------------------------

Edit:

Die Klasse wurde in folgendem Commit entfernt:

https://github.com/ZUGFeRD/mustangproject/commit/9f94e460d8881ebe349aa8b640186e30f4004489

_removed a unneccessary dependency_ 

```
<dependency>
            <groupId>com.helger</groupId>
            <artifactId>ph-jaxb</artifactId>
            <version>9.5.4</version>
</dependency>
```

Aber auch, wenn ich die Dependency zu meinem Projekt hinzufüge, kommt der Fehler. 

--------------------------------

Edit:

An dem Commit lag es nicht, sondern an der neuen Version von ph-schematron

**Comment by jstaerk** [comment]
ok kann ich bitte mal eine Datei haben mit der er fehlschlägt? Die automatischen Tests (validator\src\main\java\org\mustangproject\validator\ZUGFeRDValidator.java) laufen ja offensichtlich durch...

**Comment by smejkal** [comment]
Hierzu möchte ich noch Rückmeldung geben.

Der Fehler kam auch mit der Version 2.6.0 noch. Ich nutze die Library und Validator zusammen mit Birt. Somit lag der Verdacht nahe, dass sich irgendwelche Jars stören.

Zum "Spaß" hatte ich mal die Reihenfolge der beiden Mustang-Dependencies in der pom.xml getauscht. Und der Fehler war weg.

Also wollte ich von beiden Varianten die dependency:tree vergleichen. Aber der Fehler trat auch nach dem Zurücksetzen der Reihenfolge nicht mehr auf. 

Danke!

**Comment by jstaerk** [comment]
Evtl. Zusammenhang mit #297 in der 2.6.0? Aber Hauptsache es geht.
