### ISSUE TITLE
NoClassDefFoundError: Failed to link ch/qos/logback/classic/servlet/LogbackServletContainerInitializer

### ISSUE THREAD

**Issue by Cakmakli-a** [ZUGFeRD/mustangproject#310]
Mit dem Update auf 2.6.1 wird folgender Fehler geworfen:

```
14:39:12,509 WARN  [org.jboss.modules.define] (MSC service thread 1-2) Failed to define class ch.qos.logback.classic.servlet.LogbackServletContainerInitializer in Module "org.mustangproject:2.6.1" version 2.6.1 from local module loader @7ce3cb8e (finder: local module finder @78b66d36 (roots: E:\servers\erpservermigration\jboss-eap-7.3\modules,E:\servers\erpservermigration\jboss-eap-7.3\modules\system\layers\base\.overlays\layer-base-jboss-eap-7.3.7.CP,E:\servers\erpservermigration\jboss-eap-7.3\modules\system\layers\base)): java.lang.NoClassDefFoundError: Failed to link ch/qos/logback/classic/servlet/LogbackServletContainerInitializer (Module "org.mustangproject:2.6.1" version 2.6.1 from local module loader @7ce3cb8e (finder: local module finder @78b66d36 (roots: E:\servers\erpservermigration\jboss-eap-7.3\modules,E:\servers\erpservermigration\jboss-eap-7.3\modules\system\layers\base\.overlays\layer-base-jboss-eap-7.3.7.CP,E:\servers\erpservermigration\jboss-eap-7.3\modules\system\layers\base))): javax/servlet/ServletContainerInitializer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:753)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.wildfly.extension.undertow.deployment.ServletContainerInitializerDeploymentProcessor.deploy(ServletContainerInitializerDeploymentProcessor.java:117)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:176)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.lang.Thread.run(Thread.java:748)

...

Caused by: java.lang.NoClassDefFoundError: Failed to link ch/qos/logback/classic/servlet/LogbackServletContainerInitializer (Module "org.mustangproject:2.6.1" version 2.6.1 from local module loader @7ce3cb8e (finder: local module finder @78b66d36 (roots: E:\servers\erpservermigration\jboss-eap-7.3\modules,E:\servers\erpservermigration\jboss-eap-7.3\modules\system\layers\base\.overlays\layer-base-jboss-eap-7.3.7.CP,E:\servers\erpservermigration\jboss-eap-7.3\modules\system\layers\base))): javax/servlet/ServletContainerInitializer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:753)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

Zum Einsatz kommt ein JBoss 7.3. Hat noch jemand das Problem?

**Comment by jstaerk** [comment]
steps to reproduce?

**Comment by Cakmakli-a** [comment]
it's ok. i found the solution.
