### ISSUE TITLE
Mustang-CLI 2.11.0 process fails with exitcode 4294967295

### ISSUE THREAD

**Issue by hvbtup** [ZUGFeRD/mustangproject#417]
I'm using Mustang-CLI 2.11.0 to validate a ZUGFeRD PDF.

The process exits with the exitcode shown in the title (I guess that means -1).

I don't see any obvious errors in the file.
BTW the KOSIT validator validates the XML contained in the PDF.

This is how I call it (from Python):

```
import subprocess
args = ['E:\\lisa_ins\\reporting-223-libs\\jdk\\jre\\bin\\java.exe',
 '-jar', 'E:\\lisa_ins\\ewu\\LISA10_AUFTRAG\\reporting\\jlib\\mustang\\Mustang-CLI-2.11.0.jar', 
 '--action', 'validate', '--no-notices',
 '--source', 'E:\\lisa_ins\\ewu\\LISA10_AUFTRAG\\reporting\\lrs1_jout\\20240719-4285148\\20240719-4285148.pdf'
]
subprocess.check_call(args)
```

The Mustang output is quite lengthy, so I skip most of it here:

```

... Juli 19, 2024 1:28:19 PM org.verapdf.gf.model.factory.operators.OperatorParser parseOperator
WARNUNG: Special graphics state operator (cm) inside Text object
... This message is repeated a lot
...
Juli 19, 2024 1:28:19 PM org.verapdf.gf.model.factory.operators.OperatorParser parseOperator
WARNUNG: Special graphics state operator (cm) inside Text object
13:28:19.854 [main] INFO  c.h.s.x.SchematronResourceXSLTCache - Compiling XSLT instance [cpPath=/xslt/ZF_221/FACTUR-X_EN
16931.xslt; urlResolved=true; URL=jar:file:/E:/lisa_ins/ewu/LISA10_AUFTRAG/reporting/jlib/mustang/Mustang-CLI-2.11.0.jar
!/xslt/ZF_221/FACTUR-X_EN16931.xslt]
13:28:22.617 [main] INFO  c.h.s.x.SchematronResourceXSLTCache - Compiling XSLT instance [cpPath=/xslt/cii16931schematron
/EN16931-CII-validation.xslt; urlResolved=true; URL=jar:file:/E:/lisa_ins/ewu/LISA10_AUFTRAG/reporting/jlib/mustang/Must
ang-CLI-2.11.0.jar!/xslt/cii16931schematron/EN16931-CII-validation.xslt]
13:28:22.976 [main] INFO  o.m.validator.ZUGFeRDValidator - Parsed PDF:invalid XML:invalid Signature:null Checksum:9AE81D
06364E7B1D18E1688E743B4DEA649EADE0 Profile:urn:cen.eu:en16931:2017 Version:2 Took:4655ms Errors:[]
<?xml version="1.0" encoding="UTF-8"?>

<validation filename="20240719-4285148.pdf" datetime="2024-07-19 13:28:18">
  <pdf>ValidationResult [flavour=3b, totalAssertions=10297, assertions=[TestAssertion [ruleId=RuleId [specification=ISO
19005-3:2012, clause=6.2.8, testNumber=3], status=failed, message=If an Image dictionary contains the Interpolate key, i
ts value shall be false. For an inline image, the I key shall have a value of false., location=Location [level=CosDocume
nt, context=root/document[0]/pages[0](8 0 obj PDPage)/contentStream[0]/operators[4]/xObject[0]/contentStream[0](19 0 obj
 PDContentStream)/operators[794]/xObject[0](39 0 obj PDXImage)], locationContext=null, errorMessage=The value of the Int
erpolate key in the Image dictionary is true], TestAssertion [ruleId=RuleId [specification=ISO 19005-3:2012, clause=6.2.
11.4, testNumber=4], status=failed, message=If the FontDescriptor dictionary of an embedded CID font contains a CIDSet s
tream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is
 referenced or used by the PDF or not., location=Location [level=CosDocument, context=root/document[0]/pages[0](8 0 obj
PDPage)/contentStream[0]/operators[33]/font[0](NMSIBJ+Arial-BoldMT)/DescendantFonts[0](NMSIBJ+Arial-BoldMT)], locationCo
ntext=null, errorMessage=A CIDSet entry in the Font descriptor does not correctly identify all glyphs present in the emb
edded font subset], TestAssertion [ruleId=RuleId [specification=ISO 19005-3:2012, clause=6.2.11.4, testNumber=4], status
=failed, message=If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identi
fy all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the
PDF or not., location=Location [level=CosDocument, context=root/document[0]/pages[0](8 0 obj PDPage)/contentStream[0]/op
erators[41]/font[0](FOTADM+ArialMT)/DescendantFonts[0](FOTADM+ArialMT)], locationContext=null, errorMessage=A CIDSet ent
ry in the Font descriptor does not correctly identify all glyphs present in the embedded font subset], TestAssertion [ru
leId=RuleId [specification=ISO 19005-3:2012, clause=6.2.8, testNumber=3], status=failed, message=If an Image dictionary
contains the Interpolate key, its value shall be false. For an inline image, the I key shall have a value of false., loc
ation=Location [level=CosDocument, context=root/document[0]/pages[1](9 0 obj PDPage)/contentStream[0]/operators[4]/xObje
ct[0]/contentStream[0](24 0 obj PDContentStream)/operators[674]/xObject[0](48 0 obj PDXImage)], locationContext=null, er
rorMessage=The value of the Interpolate key in the Image dictionary is true], TestAssertion [ruleId=RuleId [specificatio
n=ISO 19005-3:2012, clause=6.2.11.4, testNumber=4], status=failed, message=If the FontDescriptor dictionary of an embedd
ed CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless
of whether a CID in the font is referenced or used by the PDF or not., location=Location [level=CosDocument, context=roo
t/document[0]/pages[1](9 0 obj PDPage)/contentStream[0]/operators[97]/font[0](CYIVFJ+Arial-ItalicMT)/DescendantFonts[0](
CYIVFJ+Arial-ItalicMT)], locationContext=null, errorMessage=A CIDSet entry in the Font descriptor does not correctly ide
ntify all glyphs present in the embedded font subset]], isCompliant=false]
    <info>
      <signature>unknown</signature>
      <duration unit="ms">1166</duration>
    </info>
    <summary status="invalid"/>
  </pdf>
  <xml>
    <info>
      <version>2</version>
      <profile>urn:cen.eu:en16931:2017</profile>
      <validator version="2.11.0"/>
      <rules>
        <fired>154</fired>
        <failed>0</failed>
      </rules>
      <duration unit="ms">3211</duration>
    </info>
    <summary status="valid"/>
  </xml>
  <summary status="invalid"/>
</validation>

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['E:\\lisa_ins\\reporting-223-libs\\jdk\\jre\\bin\\java.exe', '-jar', 'E:\\lisa_ins\\ewu\\LISA10_AUFTRAG\\reporting\\jlib\\mustang\\Mustang-CLI-2.11.0.jar', '--action', 'validate', '--no-notices', '--source', 'E:\\lisa_ins\\ewu\\LISA10_AUFTRAG\\reporting\\lrs1_jout\\20240719-4285148\\20240719-4285148.pdf']' returned non-zero exit status 4294967295.
```

**Comment by jstaerk** [comment]
The report says the surrounding PDF/A file is invalid, if you want to crosscheck try verapdf.

**Comment by hvbtup** [comment]
I understand that the VeraPDF complains about the PDF (though one of the findings is duet to a bug in VeraPDF).
But an exitcode like `4294967295` just looks like a bug in the Mustang program. The exitcodes should be zero for success or positive for an error.

**Comment by jstaerk** [comment]
I may have used -1 for an error and I wasnt aware of positive ints, but feel free to PR
