### ISSUE TITLE
NullPointerException if dueDate is not set

### ISSUE THREAD

**Issue by vmuth85** [ZUGFeRD/mustangproject#440]
I'm getting a NullPointerException in the ZUGFeRD2PullProvider.java line 303 if dueDate is not set. As far as I know, due date is not a mandatory .

```
} else if ((paymentTermsDescription == null) && (trans.getDocumentCode() != DocumentCodeTypeConstants.CORRECTEDINVOICE) && (trans.getDocumentCode() != DocumentCodeTypeConstants.CREDITNOTE)) {
			paymentTermsDescription = "Please remit until " + germanDateFormat.format(trans.getDueDate());

		}
```

```
java.lang.NullPointerException: date must not be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[na:na]
	at java.base/java.util.Calendar.setTime(Calendar.java:1792) ~[na:na]
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:978) ~[na:na]
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:971) ~[na:na]
	at java.base/java.text.DateFormat.format(DateFormat.java:378) ~[na:na]
	at org.mustangproject.ZUGFeRD.ZUGFeRD2PullProvider.generateXML(ZUGFeRD2PullProvider.java:303) ~[library-2.12.0.jar:na]
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3.prepare(ZUGFeRDExporterFromA3.java:647) ~[library-2.12.0.jar:na]
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3.setTransaction(ZUGFeRDExporterFromA3.java:642) ~[library-2.12.0.jar:na]
```

**Comment by langfr** [comment]
Die Business-Rule BRCO-25 sagt dazu:
Im Falle eines positiven Zahlbetrags "Amount due for payment" (BT-115) muss entweder das Element Fälligkeitsdatum "Payment due date" (BT-9) oder das Element Zahlungsbedingungen "Payment terms" (BT-20) vorhanden sein.

In den oben beschriebenen Fehler läuft man nur, wenn man weder noch angegeben hat.
Sollte aber trotzdem nicht zu einer NullPointerException führen.

**Comment by langfr** [comment]
PR #441 created.

**Comment by vmuth85** [comment]
Danke für die Umsetzung!
