### ISSUE TITLE
ArithmeticException due to prime number division in LineCalculator

### ISSUE THREAD

**Issue by fktrdui** [ZUGFeRD/mustangproject#443]
An ArithmeticException occurs in the LineCalculator class when performing calculations involving division by a prime number, specifically 31 in this case. This leads to a non-terminating decimal expansion that BigDecimal cannot represent exactly.

Steps to Reproduce:
Mustang version: 2.11.0

1. Use LineCalculator with these values:
   - Quantity: 30.00
   - Price: 15.00
   - BasisQuantity: 31.00
   - Unit: Day

2. Error occurs on this line (LineCalculator.java:42):
   itemTotalNetAmount = currentItem.getQuantity().multiply(getPrice()).divide(currentItem.getBasisQuantity())
                        .subtract(allowanceItemTotal).setScale(2, RoundingMode.HALF_UP);

Error Message:
java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
    at java.base/java.math.BigDecimal.divide(BigDecimal.java:1780)
    at org.mustangproject.ZUGFeRD.LineCalculator.<init>(LineCalculator.java:42)

Potential Solutions to Consider:
1. Specify precision and rounding mode for all divisions:
   .divide(currentItem.getBasisQuantity(), 10, RoundingMode.HALF_UP)

**Comment by melo0187** [comment]
Funny enough, I just encountered the same issue with Mustang version 2.12.0 and an invoice with Quantity 31 and BasisQuantity 366 and Unit Day.
