### ISSUE TITLE
JSon deserialization does not work with BankDetails

### ISSUE THREAD

**Issue by phermsdorf** [ZUGFeRD/mustangproject#455]
Hi,

when adding something like

.addBankDetails(new BankDetails("DE3600000123456", "ABCDEFG1001").setAccountName("Donald Duck")))

to the sender of the Invoice in the test DeSerializationTest.java i get the following exception in my setup:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.mustangproject.BankDetails` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"documentName":null,"documentCode":"380","num
 <snip>
 "[truncated 5869 chars]; line: 1, column: 876] (through reference chain: org.mustangproject.Invoice["sender"]->org.mustangproject.TradeParty["bankDetails"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)

```
I suspect that the default constructor and/or the `@JsonIgnoreProperties` annotation is missing from the BankDetails class which is present on most other classes related to the Invioce.

What do you mean?

I could provide a pull request for that change (next week or so) if you want.

Bye Peterr

**Comment by jstaerk** [comment]
thank you, the assumption wans not entirely correct but correct enough to guide the way :-)

**Comment by phermsdorf** [comment]
Thanks you!
