### ISSUE TITLE
Files missing in actual commit

### ISSUE THREAD

**Issue by doku-san** [ZUGFeRD/mustangproject#46]
Hi, I tried to get the project working, but I have several issues:

1. There are only 10 Classes in the model, but about 47 referenced in ZUGFeRDTransactionModelConverter.java
2. Dependency com.sanityinc.jargs could not be resolved.

Any Ideas?

**Comment by jstaerk** [comment]
do you have the current and clean version, i.e. did you fetch and pull?

```
git fetch --all
git reset --hard origin/master
mvn clean package
```
could help. 47 referenced files sounds like the version when I tried to get ZF2 running with JAXB.

For jargs you were right, apologies.
I had forgotten to include the sonatype-oss-public repository in the parent POMfile when I moved toecount upwards, thats now fixed.

**Comment by doku-san** [comment]
Hi, thanks for you hints. I did work on the latest branch and updated as you mentioned.

But the error still remained ... until I changed my $JAVA_HOME$ from JRE to JDK. That fixed it for me. Thanks

**Comment by doku-san** [comment]
Sorry to bother you again. The last version working for me is 1.3.1. That was the Version working.

In actual Version files are missing. See https://github.com/ZUGFeRD/mustangproject/blob/master/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDTransactionModelConverter.java
There are 47 Model Imports and not resolving anywhere, because these Files are missing.

**Comment by jstaerk** [comment]
@doku-san if you have steps to reproduce feel free to reopen the issue. I tried

```
git clone git@github.com:ZUGFeRD/mustangproject.git
cd mustangproject
mvn clean package
```

and that worked perfectly. AFAIK the files that you mention are generated automatically from the schema file in the xjc goal of the pom file.

**Comment by doku-san** [comment]
Maybe that's the point. I imported the project into eclipse...

But reproducing the steps you mentioned I went into some errors, when the tests were executed:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Ung³ltiges Byte 2 von 2-Byte-UTF-8-Sequenz.
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:372)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.peekChar(XMLEntityScanner.java:508)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2716)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.parse(ZUGFeRDImporter.java:134)
        at org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest.testZExport(MustangReaderWriterCustomXMLTest.java:218)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:255)
        at junit.framework.TestSuite.run(TestSuite.java:250)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.493 sec <<< FAILURE!
testZExport(org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest)  Time elapsed: 2.406 sec  <<< ERROR!
java.lang.NullPointerException
        at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.parse(ZUGFeRDImporter.java:144)
        at org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest.testZExport(MustangReaderWriterCustomXMLTest.java:218)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:255)
        at junit.framework.TestSuite.run(TestSuite.java:250)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.mustangproject.ZUGFeRD.MustangReaderWriterEdgeTest
Okt 10, 2017 6:32:59 PM org.apache.pdfbox.cos.COSDocument finalize
WARNUNG: Warning: You did not close a PDF Document
Okt 10, 2017 6:32:59 PM org.apache.pdfbox.pdfparser.COSParser parseCOSStream
WARNUNG: The stream doesn't provide any stream length, using fallback readUntilEnd, at offset 1004
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.727 sec
Running org.mustangproject.ZUGFeRD.MustangReaderWriterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.587 sec
Running org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverterTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.928 sec

Results :

Tests in error:
  testZExport(org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest)

Tests run: 7, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.474 s
[INFO] Finished at: 2017-10-10T18:33:02+02:00
[INFO] Final Memory: 24M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project mustang: There are test failures.
[ERROR]
[ERROR] Please refer to C:\bin\rep\mustangproject\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

C:\bin\rep\mustangproject (master)
```

I am not any pro in using maven, so maybe there is a problem in front of the computer... Actually I need a JAR with all dependencies to include it into another non-maven project.
