### ISSUE TITLE
Impossible to convert XRechnung/UBL to PDF

### ISSUE THREAD

**Issue by zeratools** [ZUGFeRD/mustangproject#481]
Hello,

I don't find a way to handle XRechnung format V3.0 as produced by this generator https://xrechnung-erstellen.com/#generator

I try both as a Java library (wich is my target) or with the cli but I can't find a way to process the file (zipped example linked).
[XRechnung_3.zip](https://github.com/user-attachments/files/17027843/XRechnung_3.zip)

Here is an extract of what the generated file looks like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cec="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
  <cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</cbc:CustomizationID>
  <cbc:ProfileID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</cbc:ProfileID>
  <cbc:ID>gdfgdf gdfgdsfsd</cbc:ID>
  <cbc:IssueDate>2024-09-17</cbc:IssueDate>
  <cbc:DueDate>2024-09-20</cbc:DueDate>
  <cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>
  <cbc:DocumentCurrencyCode>EUR</cbc:DocumentCurrencyCode>
  <cbc:BuyerReference>B2B_Rechnung</cbc:BuyerReference>
  <cac:AccountingSupplierParty>
    <cac:Party>
      <cbc:EndpointID schemeID="EM">fds@fsd.fr</cbc:EndpointID>
      <cac:PartyName>
        <cbc:Name>fsdfsd</cbc:Name>
      </cac:PartyName>
...
```

Using the cli I get the following issue and the same exception message using the Java Library:

```
java -Dfile.encoding=UTF-8 -jar Mustang-CLI-2.13.0.jar --action pdf
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
ZUGFeRD XML source (default: factur-x.xml):XRechnung.xml
Target file (default: factur-x.pdf):XRechnung.xml.pdf
Error on line 2 column 3
  SXXP0003   Error reported by XML parser: Content is not allowed in prolog.
Error
  SXXP0003  SXXP0003   Error reported by XML parser: Content is not allowed in prolog.
Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "result" is null
Written to XRechnung.xml.pdf
```

I get the same result with this similar file https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/business-cases/standard/01.01a-INVOICE_ubl.xml.

Could you give me an advice on this subject, maybe I don't use the right options or is it a bug with these xrechnung v3 UBL files ?

I will be happy to provide any other information needed.

Best regard,
Vincent

**Comment by landrix** [comment]
the xrechnung v3 UBL files are valid

**Comment by zeratools** [comment]
I'm glad they are valid but in that case it means it's a bug in the library I guess.

Here is a simple code which allow me to reproduce the issue :
```java
package com.example;

import org.mustangproject.ZUGFeRD.XRechnungImporter;
import org.mustangproject.ZUGFeRD.ZUGFeRDVisualizer;

public class Demat {

    public static void main(String[] args) throws Exception {

        final String xmlFile = "\\\\wsl.localhost\\Ubuntu\\home\\vmigot\\01.01a-INVOICE_ubl.xml";

        XRechnungImporter xi = new XRechnungImporter(xmlFile);

        if (xi.containsMeta()) {
            System.out.println("--> XML Contains Meta Data");
        } else {
            throw new Exception("XML Contains NO Meta Data");
        }

        if (xi.canParse()) {
            System.out.println("--> XML can be parsed");
        } else {
            // -->Program goes HERE ??!!
            System.out.println("--> XML can NOT be parsed");
            System.out.println("METADATA :");
            System.out.println("----------");
            System.out.println(xi.getMeta());
        }

        System.out.println("--> Try to generate PDF");
        ZUGFeRDVisualizer zv = new ZUGFeRDVisualizer();
        zv.toPDF(xmlFile, xmlFile + ".pdf");
    }
}
```

And the result I get using the file mentionend previously https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/business-cases/standard/01.01a-INVOICE_ubl.xml

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
--> XML Contains Meta Data
--> XML can NOT be parsed
METADATA :
----------
<?xml version="1.0" encoding="UTF-8"?>
<ubl:Invoice xmlns:ubl="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
             xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
             xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
    <cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</cbc:CustomizationID>
    <cbc:ProfileID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</cbc:ProfileID>
    <cbc:ID>123456XX</cbc:ID>
    <cbc:IssueDate>2016-04-04</cbc:IssueDate>
    <cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>
    <cbc:Note>#ADU#Es gelten unsere Allgem. Geschäftsbedingungen, die Sie unter […] finden.</cbc:Note>
    <cbc:DocumentCurrencyCode>EUR</cbc:DocumentCurrencyCode>
    <cbc:BuyerReference>04011000-12345-03</cbc:BuyerReference>
    <cac:AccountingSupplierParty>
        <cac:Party>
            <cbc:EndpointID schemeID="EM">seller@email.de</cbc:EndpointID>
            <cac:PartyName>
                <cbc:Name>[Seller trading name]</cbc:Name>
            </cac:PartyName>
            <cac:PostalAddress>
                <cbc:StreetName>[Seller address line 1]</cbc:StreetName>
                <cbc:CityName>[Seller city]</cbc:CityName>
                <cbc:PostalZone>12345</cbc:PostalZone>
                <cac:Country>
                    <cbc:IdentificationCode>DE</cbc:IdentificationCode>
                </cac:Country>
            </cac:PostalAddress>
            <cac:PartyTaxScheme>
                <cbc:CompanyID>DE 123456789</cbc:CompanyID>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:PartyTaxScheme>
            <cac:PartyLegalEntity>
                <cbc:RegistrationName>[Seller name]</cbc:RegistrationName>
                <cbc:CompanyID>[HRA-Eintrag]</cbc:CompanyID>
                <cbc:CompanyLegalForm>123/456/7890, HRA-Eintrag in […]</cbc:CompanyLegalForm>
            </cac:PartyLegalEntity>
            <cac:Contact>
                <cbc:Name>nicht vorhanden</cbc:Name>
                <cbc:Telephone>+49 1234-5678</cbc:Telephone>
                <cbc:ElectronicMail>seller@email.de</cbc:ElectronicMail>
            </cac:Contact>
        </cac:Party>
    </cac:AccountingSupplierParty>
    <cac:AccountingCustomerParty>
        <cac:Party>
            <cbc:EndpointID schemeID="EM">buyer@info.de</cbc:EndpointID>
            <cac:PartyIdentification>
                <cbc:ID>[Buyer identifier]</cbc:ID>
            </cac:PartyIdentification>
            <cac:PostalAddress>
                <cbc:StreetName>[Buyer address line 1]</cbc:StreetName>
                <cbc:CityName>[Buyer city]</cbc:CityName>
                <cbc:PostalZone>12345</cbc:PostalZone>
                <cac:Country>
                    <cbc:IdentificationCode>DE</cbc:IdentificationCode>
                </cac:Country>
            </cac:PostalAddress>
            <cac:PartyLegalEntity>
                <cbc:RegistrationName>[Buyer name]</cbc:RegistrationName>
            </cac:PartyLegalEntity>
        </cac:Party>
    </cac:AccountingCustomerParty>
    <cac:PaymentMeans>
        <cbc:PaymentMeansCode>58</cbc:PaymentMeansCode>
        <cac:PayeeFinancialAccount>
            <!-- dies ist eine nicht existerende aber valide IBAN als test dummy -->
            <cbc:ID>DE75512108001245126199</cbc:ID>
        </cac:PayeeFinancialAccount>
    </cac:PaymentMeans>
    <cac:PaymentTerms>
        <cbc:Note>Zahlbar sofort ohne Abzug.</cbc:Note>
    </cac:PaymentTerms>
    <cac:TaxTotal>
        <cbc:TaxAmount currencyID="EUR">22.04</cbc:TaxAmount>
        <cac:TaxSubtotal>
            <cbc:TaxableAmount currencyID="EUR">314.86</cbc:TaxableAmount>
            <cbc:TaxAmount currencyID="EUR">22.04</cbc:TaxAmount>
            <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>7</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:TaxCategory>
        </cac:TaxSubtotal>
    </cac:TaxTotal>
    <cac:LegalMonetaryTotal>
        <cbc:LineExtensionAmount currencyID="EUR">314.86</cbc:LineExtensionAmount>
        <cbc:TaxExclusiveAmount currencyID="EUR">314.86</cbc:TaxExclusiveAmount>
        <cbc:TaxInclusiveAmount currencyID="EUR">336.9</cbc:TaxInclusiveAmount>
        <cbc:PayableAmount currencyID="EUR">336.9</cbc:PayableAmount>
    </cac:LegalMonetaryTotal>
    <cac:InvoiceLine>
        <cbc:ID>Zeitschrift [...]</cbc:ID>
        <cbc:Note>Die letzte Lieferung im Rahmen des abgerechneten Abonnements erfolgt in 12/2016 Lieferung erfolgt / erfolgte direkt vom Verlag</cbc:Note>
        <cbc:InvoicedQuantity unitCode="XPP">1</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="EUR">288.79</cbc:LineExtensionAmount>
        <cac:InvoicePeriod>
            <cbc:StartDate>2016-01-01</cbc:StartDate>
            <cbc:EndDate>2016-12-31</cbc:EndDate>
        </cac:InvoicePeriod>
        <cac:OrderLineReference>
            <cbc:LineID>6171175.1</cbc:LineID>
        </cac:OrderLineReference>
        <cac:Item>
            <cbc:Description>Zeitschrift Inland</cbc:Description>
            <cbc:Name>Zeitschrift [...]</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>246</cbc:ID>
            </cac:SellersItemIdentification>
            <cac:CommodityClassification>
                <cbc:ItemClassificationCode listID="IB">0721-880X</cbc:ItemClassificationCode>
            </cac:CommodityClassification>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>7</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">288.79</cbc:PriceAmount>
        </cac:Price>
    </cac:InvoiceLine>
    <cac:InvoiceLine>
        <cbc:ID>Porto + Versandkosten</cbc:ID>
        <cbc:InvoicedQuantity unitCode="XPP">1</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="EUR">26.07</cbc:LineExtensionAmount>
        <cac:Item>
            <cbc:Name>Porto + Versandkosten</cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>7</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">26.07</cbc:PriceAmount>
        </cac:Price>
    </cac:InvoiceLine>
</ubl:Invoice>
Warning at char 27 in xsl:value-of/@select on line 1985 column 166 
  SXWN9026: Comparison of xs:untypedAtomic? to xs:boolean will fail unless the first operand is empty
Warning at xsl:for-each on line 2083 column 78 
  SXWN9009: An empty xsl:for-each instruction has no effect
Warning at char 6 in xsl:value-of/@select on line 1010 column 126 
  SXWN9026: Comparison of xs:untypedAtomic? to xs:boolean will fail unless the first operand is empty
Warning at char 6 in xsl:value-of/@select on line 1927 column 119 
  SXWN9026: Comparison of xs:untypedAtomic? to xs:boolean will fail unless the first operand is empty
Error on line 2 column 5 
  SXXP0003   Error reported by XML parser: Content is not allowed in prolog.
Error 
  SXXP0003  SXXP0003   Error reported by XML parser: Content is not allowed in prolog.
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "result" is null
	at org.mustangproject.ZUGFeRD.ZUGFeRDVisualizer.toPDF(ZUGFeRDVisualizer.java:325)
	at com.example.Demat.main(DematDe.java:50)
```

**Comment by jstaerk** [comment]
yes, confirmed, thats a bug, conversion to html works and if you convert it to cii like
this [invoice-target.txt](https://github.com/user-attachments/files/17077136/invoice-target.txt)
  it also converts to pdf like that
[factur-x.pdf](https://github.com/user-attachments/files/17077138/factur-x.pdf)

**Comment by zeratools** [comment]
Hello and thank you.
I tested it today and it's working perfectly on the master branch.
Any idea when will the 2.15.0 release will be available including this fix ?

Best regards.

**Comment by jstaerk** [comment]
probably still in october.
