### ISSUE TITLE
ZUGFeRDImporter broken: NoSuchMethodError

### ISSUE THREAD

**Issue by uwemock** [ZUGFeRD/mustangproject#55]
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.common.filespecification.PDEmbeddedFile.getByteArray()[B
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extractLowLevel(ZUGFeRDImporter.java:107)
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extract(ZUGFeRDImporter.java:64)
	at de.uwemock.eur.gui.metadata.ZUGFeRD.containsZUGFeRD(ZUGFeRD.java:17)

This happens in 1.4.0 as well as in 1.5.1.

**Comment by jstaerk** [comment]
In the jar version or also in the maven version?
The interesting thing is that I recently sucessfully tested http://www.mustangproject.org/use.html#read 
I suspect this could be a duplicate of #53 , i.e. some pdfbox version conflict

**Comment by uwemock** [comment]
Yes, finally found out.
ZUGFeRDImporter requires PDFBox version 1.8.x.

**Comment by jstaerk** [comment]
Strange, within the build process of 1.5.0/1.5.1 i thought it was (only) 2.0.8 and now 2.0.9 is required in the POM. Can you provide me with a sample project where it does not work?

**Comment by jstaerk** [comment]
@uwemock does this still persist?

**Comment by uwemock** [comment]
I can't tell. Maven search doesn't find mustangproject any more. My pom uses 1.2.0.

**Comment by uwemock** [comment]
I had this issue with 1.7.2 again.
In order to get around it, I removed org.apache.pdfbox:preflight from my dependencies and replaced it by commons-io.
