### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal base64 character 20

### ISSUE THREAD

**Issue by uwemock** [ZUGFeRD/mustangproject#560]
I get an exception with [one of the example files from the KOSIT suite](https://projekte.kosit.org/xrechnung/xrechnung-visualization/-/blob/master/src/test/instances/embedded-documents-with-newline-and-whitespace_ubl.xml?ref_type=heads):

```
java.lang.IllegalArgumentException: Illegal base64 character 20
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter.extractInto(ZUGFeRDInvoiceImporter.java:342)
	at org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter.extractInvoice(ZUGFeRDInvoiceImporter.java:459)
```

**Comment by ThomasChr** [comment]
There is an attached document in BASE64 format inside the xml. Seems that 0x20 (line break) isn‘t stripped before parsing the BASE64 payload. 0x20 isn‘t valid in BASE64.

**Comment by uwemock** [comment]
The document validates against UBL-Invoice-2.1.xsd, so one should be able to retrieve the metadata. The exception should be handled in ```ZUGFeRDInvoiceImporter.extractInto``` so the attachment will be missing. The client should not have to cope with that kind of (low level) exception.

(0x20 is a space character, btw)
