### ISSUE TITLE
Error when converting PDF/A-1 to PDF/A-3

### ISSUE THREAD

**Issue by dgnthr** [ZUGFeRD/mustangproject#58]
Hi,

when I want to convert PDF/A-1 to PDF/A-3 with mustang I get the following exception:

> java.io.IOException: File must be attached (usually with PDFattachZugferdFile) before perfoming this operation
>        at org.mustangproject.ZUGFeRD.ZUGFeRDExporter.export(ZUGFeRDExporter.java:337)
>        at org.mustangproject.toecount.Toecount.main(Toecount.java:391)
>Written to invoice.a3.pdf

The resultfile isn't written. The input I use is PDF/A-1 compatible as checked with VeraPdf.

Thank you for looking into it.

**Comment by jstaerk** [comment]
Thanks. The error message is gone in the current master, I uploaded a binary to http://mustangproject.org/deploy/mustang-1.5.3-SNAPSHOT.jar . I'm not yet sure if the result is particularly valid, though :-/.
