### ISSUE TITLE
Using 2.14.2, got some errors from demo zugferd 1 pdf's

### ISSUE THREAD

**Issue by willie68** [ZUGFeRD/mustangproject#594]
I'm just updating from 2.13.0 to 2.14.2 (because 2.15 will not work, because api changes and much more problems, see #572)
I got an error from some of the demo zugpferd 1 pdfs, when i try to extract the invoice via "ZUGFeRDInvoiceImporter.extractInvoice"

Java trace:
java.lang.NullPointerException: Cannot invoke "org.mustangproject.ZUGFeRD.IZUGFeRDExportableProduct.getVATPercent()" because the return value of "org.mustangproject.ZUGFeRD.IZUGFeRDExportableItem.getProduct()" is null

	at org.mustangproject.ZUGFeRD.LineCalculator.<init>(LineCalculator.java:37)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657)
	at org.mustangproject.ZUGFeRD.TransactionCalculator.getTotal(TransactionCalculator.java:142)
	at org.mustangproject.ZUGFeRD.TransactionCalculator.getTaxBasis(TransactionCalculator.java:153)
	at org.mustangproject.ZUGFeRD.TransactionCalculator.getGrandTotal(TransactionCalculator.java:49)
	at org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter.extractInto(ZUGFeRDInvoiceImporter.java:420)
	at org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter.extractInvoice(ZUGFeRDInvoiceImporter.java:459)
	
If you like i can provide the pdfs...

**Comment by willie68** [comment]
the demo files are coming from corpus, [ZUGFeRDv1/correct/Intarsys](https://github.com/ZUGFeRD/corpus/tree/master/ZUGFeRDv1/correct/Intarsys)
zugferd_1p0_extended* as an example...
Or are these files incorrect?
