### ISSUE TITLE
Combine with ZUGFeRD v2: NullPointerException

### ISSUE THREAD

**Issue by Indigo744** [ZUGFeRD/mustangproject#68]
I created a test file containing a few words in Microsoft Word, and I generated a PDF/A1 file (using the relevant option when outputing the PDF). This file is validated successfully as PDF/A1 using [online ](https://www.pdf-online.com/osa/validate.aspx) [validators](https://www.pdfen.com/pdf-a-validator).

However, when I use the combine option (with the sample file ZUGFeRD2-invoice.xml)
```
java -jar mustang-1.5.5-SNAPSHOT.jar -c --source "test.pdf" --source-xml "ZUGFeRD2-invoice.xml" --out "out.pdf" --zugferd-version 2 --zugferd-profile m
```

I get (with any profile, actually):

```
java.lang.NullPointerException
        at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter$Totals.<init>(ZUGFeRDTransactionModelConverter.java:1042)
        at org.mustangproject.ZUGFeRD.ZUGFeRDTransactionModelConverter.<init>(ZUGFeRDTransactionModelConverter.java:90)
        at org.mustangproject.ZUGFeRD.ZUGFeRD1PullProvider.createZugferdXMLForTransaction(ZUGFeRD1PullProvider.java:61)
        at org.mustangproject.ZUGFeRD.ZUGFeRD1PullProvider.generateXML(ZUGFeRD1PullProvider.java:89)
        at org.mustangproject.ZUGFeRD.ZUGFeRDExporter.PDFattachZugferdFile(ZUGFeRDExporter.java:328)
        at org.mustangproject.ZUGFeRD.ZUGFeRDExporter.setZUGFeRDXMLData(ZUGFeRDExporter.java:453)
        at org.mustangproject.toecount.Toecount.performCombine(Toecount.java:511)
        at org.mustangproject.toecount.Toecount.main(Toecount.java:298)
```

Note that it does work if I use ZUGFeRD v1.

This sample file can be found here: https://we.tl/t-59RVwfXbmf

**Comment by jstaerk** [comment]
I'll try to reproduce tonight

**Comment by jstaerk** [comment]
It seems to be related to the fact that when exporting a ZF2 file programmatically, a ZF1 file with identical data is also attached. This is done in 
ZUGFeRDExporter ll 325-334 and when commented out it works. It's obvious that ZF1 can't be generated at all when the XML data had been feeded, i.e. no generator is present at all. This might have been broken in previous versions as well but the dual export had been added not so long ago.

Tomorrow I have more time to look into it and potentially even fix it and if I'm super lucky me or someone else would also write an automated test to avoid that from happening again.

**Comment by Indigo744** [comment]
Thanks. When do you plan to release a new version?
