### ISSUE TITLE
factur-x sample 0023 does not validate

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#88]
[Facture_F20180023_EN_16931.pdf](https://github.com/ZUGFeRD/mustangproject/files/3199494/Facture_F20180023_EN_16931.pdf)

seems to return ```<xml><info><version>invalid</version><profile>invalid</profile><duration unit="ms">23</duration></info><messages><exception type="22">Content is not allowed in prolog.<stacktrace>org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)	at ZUV.XMLValidator.validate(XMLValidator.java:140)	at ZUV.Main.run(Main.java:142)	at ZUV.Main.main(Main.java:168)</stacktrace></exception></messages><summary status="invalid"></summary></xml>``` instead of
```
<xml>
<info><version>2</version><profile>urn:cen.eu:en16931:2017</profile><duration unit='ms'>7094</duration></info><messages><error location="/*[local-name()='CrossIndustryInvoice']/*[local-name()='SupplyChainTradeTransaction']/*[local-name()='ApplicableHeaderTradeAgreement']/*[local-name()='SellerTradeParty']/*[local-name()='URIUniversalCommunication']/*[local-name()='URIID']" criterion="document('zugferd2p0_en16931_codedb.xml')//cl[@id=8]/enumeration[@value=$codeValue8]">
    Wert von '@schemeID' ist unzulässig.</error>
</messages><summary status='invalid'/>
</xml>
```

**Comment by jstaerk** [comment]
the way it was embedded was wrong, must contain -Dfile.encoding=UTF-8
